# Generated by Django 4.2.4 on 2023-08-17 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_made',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
