# Generated by Django 4.2.4 on 2023-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
